build:
    image: default-jammy
    environment:
        php: 8.4
    nodes:
        analysis:
            project_setup:
                override: true
            dependencies:
                before:
                    - sudo apt-get update -qq
                    - sudo apt-get install -y libssl-dev pkg-config
            tests:
                override:
                    - php-scrutinizer-run

filter:
    paths: ["src/*"]
